/*
    Operators in JavaScript

    Một số thuật ngữ cần nắm:
    1. Arithmetic Operator - Toán tử số học: a+b; a%b;
    2. Unary Operators - Operator có 1 operand: count++; --number; !error ...
    3. Binary Operators - Operator có 2 operand: a=b; a+b; ...
    4. Ternary Operators - Operator có 3 operand: isShow ? "Show" : "Hide"
    5. Logical Operators - Operator luận lý: a||b; a&&b ...
    6. Bitwise Operators - Operator xử lý bit: a>>b; a|b; ...
*/