/*
    Logical Operator:
    Xét một số điều kiện như sau:
     - Nếu là số dương thì ...
     - Nếu là số dương chẵn thì ...
     - Nếu là số dương chẵn và lớn hơn 10 thì ...
     - Nếu là số dương chẵn và chia hết cho 5 và lớn hơn 10 thì ...
     - Nếu là số dương chẵn hoặc số âm lẻ thì ...
     ...

    Rõ ràng mình cần phải có một cách thức nào đó để biểu diễn các điều kiện này trong Javascript. Và đó là
    lúc mình cần tìm tới Logical Operator

    3 Logical Operator cơ bản: AND (&&), OR (||), NOT (!)
*/